import React, { useState } from 'react';
import { Book, Language } from '../types';
import { Download, Printer, ArrowLeft, FileJson, Globe, Check } from 'lucide-react';
import { dbService } from '../services/dbService';

interface BookPreviewProps {
  book: Book;
  onReset: () => void;
}

export const BookPreview: React.FC<BookPreviewProps> = ({ book, onReset }) => {
  const language = book.config.language;
  const [isPublishing, setIsPublishing] = useState(false);
  const [publishedId, setPublishedId] = useState<string | null>(null);

  const t = {
    'pt-BR': {
        alert: "Para garantir a melhor formatação (imagens full-bleed, layout editorial), recomendamos baixar a versão HTML e imprimir a partir do arquivo salvo no seu computador.",
        downloadHtml: "Baixar Versão Editorial (HTML)",
        downloadJson: "Baixar Backup (JSON)",
        publish: "Publicar na Biblioteca",
        publishing: "Publicando...",
        published: "Publicado!",
        chapter: "Capítulo",
        writtenBy: "por",
        generatedBy: "Gerado por",
        masterpiece: "Coleção Obra-prima IA",
        backCoverDesc: "Gerado com tecnologia Gemini 2.5 Flash",
        fig: "Fig",
        summary: "Sumário"
    },
    'en-US': {
        alert: "To ensure best formatting (full-bleed images, editorial layout), we recommend downloading the HTML version and printing from the saved file.",
        downloadHtml: "Download Editorial Version (HTML)",
        downloadJson: "Download Backup (JSON)",
        publish: "Publish to Library",
        publishing: "Publishing...",
        published: "Published!",
        chapter: "Chapter",
        writtenBy: "by",
        generatedBy: "Generated by",
        masterpiece: "AI Masterpiece Collection",
        backCoverDesc: "Generated with Gemini 2.5 Flash technology",
        fig: "Fig",
        summary: "Table of Contents"
    }
  }[language];
  
  const handlePrint = () => {
    alert(t.alert);
  };

  const handlePublish = async () => {
    if (publishedId) return;
    setIsPublishing(true);
    const result = await dbService.publishBook(book);
    setIsPublishing(false);
    if (result && result.success) {
        setPublishedId(result.id);
        alert("Livro publicado com sucesso na Biblioteca Pública!");
    }
  };

  const downloadJson = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(book));
    const a = document.createElement('a');
    a.href = dataStr;
    a.download = `${book.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_backup.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  const downloadHtml = () => {
    // Generate complex HTML structure for sections
    const chaptersHtml = book.chapters.map((chapter, cIdx) => {
        const sectionsHtml = chapter.sections.map((section, sIdx) => `
            <div class="section mb-16">
                ${section.imageUrl ? `
                <div class="my-8 relative group break-inside-avoid">
                   <img src="${section.imageUrl}" alt="${section.title}" class="w-full h-auto rounded-lg shadow-lg" />
                   <p class="text-xs text-gray-400 mt-2 text-center italic font-sans">${t.fig} ${cIdx+1}.${sIdx+1} — ${section.visualConcept}</p>
                </div>
                ` : ''}
                
                <h3 class="font-sans text-2xl font-bold text-[#2d2a26] mt-8 mb-4 border-l-4 border-indigo-600 pl-4">
                    ${section.title}
                </h3>
                
                <div class="prose prose-lg prose-indigo max-w-none font-serif text-gray-700 leading-relaxed text-justify">
                    ${section.content || '<p>...</p>'}
                </div>
            </div>
        `).join('');

        return `
            <article class="page-break bg-white mb-24">
                <div class="mb-16 border-b border-gray-200 pb-8">
                    <span class="text-indigo-600 font-bold uppercase tracking-widest text-sm mb-2 block">${t.chapter} ${String(cIdx + 1).padStart(2, '0')}</span>
                    <h2 class="text-5xl font-serif font-black text-[#2d2a26] leading-tight">${chapter.title}</h2>
                    <p class="text-xl text-gray-500 mt-4 font-light font-sans max-w-2xl">${chapter.description}</p>
                </div>
                ${sectionsHtml}
            </article>
        `;
    }).join('');

    const htmlContent = `
<!DOCTYPE html>
<html lang="${language}">
<head>
  <meta charset="UTF-8">
  <title>${book.title}</title>
  <script src="https://cdn.tailwindcss.com?plugins=typography"></script>
  <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400&family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <style>
    body { font-family: 'Merriweather', serif; color: #333; }
    h1, h2, h3, h4 { font-family: 'Inter', sans-serif; }
    .page-break { page-break-before: always; }
    @media print {
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      .no-print { display: none; }
    }
  </style>
</head>
<body class="bg-white text-slate-900 antialiased p-0 m-0">
  <div class="max-w-[210mm] mx-auto bg-white min-h-[297mm] p-[15mm]">
    
    <!-- Cover -->
    <div class="page-break min-h-[90vh] flex flex-col justify-center items-center text-center border-8 border-double border-indigo-900 p-12 bg-[#fafafa]">
      <div class="uppercase tracking-[0.3em] text-gray-500 text-sm mb-12">IA Books Edition</div>
      <h1 class="text-6xl font-black text-indigo-950 mb-6 leading-none">${book.title}</h1>
      <h2 class="text-3xl text-gray-600 font-light mb-16">${book.subtitle}</h2>
      <div class="w-16 h-16 bg-indigo-600 rounded-full mb-16 opacity-20"></div>
      <p class="text-lg font-bold">${t.writtenBy} ${book.config.authorName}</p>
    </div>

    <!-- TOC -->
    <div class="page-break min-h-[80vh] p-12">
        <h2 class="text-3xl font-bold mb-8 border-b pb-4">${t.summary}</h2>
        <ul class="space-y-4">
            ${book.chapters.map((c, i) => `
                <li class="flex justify-between items-baseline">
                    <span class="font-bold text-lg">${i + 1}. ${c.title}</span>
                </li>
            `).join('')}
        </ul>
    </div>

    <!-- Content -->
    ${chaptersHtml}

    <!-- Footer -->
    <div class="page-break flex items-center justify-center min-h-[50vh] bg-slate-50">
        <div class="text-center">
            <p class="text-sm text-gray-400 uppercase tracking-widest mb-2">${t.generatedBy}</p>
            <h3 class="text-2xl font-bold text-slate-800">IA Books</h3>
            <p class="text-xs text-gray-400 mt-2">Powered by Fábio Arieira</p>
        </div>
    </div>
  </div>
</body>
</html>`;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${book.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="h-full flex flex-col bg-gray-50">
      {/* Navbar */}
      <header className="h-16 bg-white border-b border-gray-200 flex items-center justify-between px-6 shadow-sm z-20 sticky top-0">
        <div className="flex items-center gap-4">
          <button onClick={onReset} className="p-2 hover:bg-gray-100 rounded-full text-gray-600">
            <ArrowLeft size={20} />
          </button>
          <h1 className="font-sans font-bold text-gray-800 truncate max-w-md">{book.title}</h1>
        </div>
        <div className="flex gap-3">
          <button 
            onClick={handlePublish}
            disabled={!!publishedId || isPublishing}
            className={`flex items-center gap-2 px-3 py-2 rounded-lg font-bold shadow-sm transition-all ${
                publishedId 
                ? 'bg-green-100 text-green-700 cursor-default' 
                : 'bg-black text-white hover:bg-gray-800'
            }`}
          >
            {isPublishing ? (
                 <div className="animate-spin h-4 w-4 border-2 border-white rounded-full border-t-transparent" />
            ) : publishedId ? (
                <Check size={18} />
            ) : (
                <Globe size={18} />
            )}
            <span className="hidden sm:inline">
                {publishedId ? t.published : isPublishing ? t.publishing : t.publish}
            </span>
          </button>

          <button onClick={downloadJson} className="flex items-center gap-2 px-3 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg font-medium shadow-sm transition-all" title="Backup Seguro">
            <FileJson size={18} /> <span className="hidden sm:inline">{t.downloadJson}</span>
          </button>
          <button onClick={downloadHtml} className="flex items-center gap-2 px-5 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg font-medium shadow transition-all">
            <Download size={18} /> <span className="hidden sm:inline">{t.downloadHtml}</span>
          </button>
          <button onClick={handlePrint} className="flex items-center gap-2 px-4 py-2 text-gray-600 hover:bg-gray-100 rounded-lg font-medium">
            <Printer size={18} />
          </button>
        </div>
      </header>

      {/* Preview Area */}
      <div className="flex-1 overflow-auto p-8 lg:p-12">
        <div className="max-w-4xl mx-auto bg-white shadow-2xl min-h-screen">
            
            {/* Digital Cover */}
            <div className="min-h-[80vh] flex flex-col justify-center items-center text-center p-20 bg-gradient-to-br from-gray-50 to-gray-200 border-b border-gray-300">
                <span className="uppercase tracking-[0.4em] text-indigo-400 text-xs font-bold mb-8">{t.masterpiece}</span>
                <h1 className="font-serif text-7xl font-black text-gray-900 mb-6 leading-[0.9]">{book.title}</h1>
                <p className="font-sans text-2xl text-gray-500 font-light max-w-2xl leading-relaxed">{book.subtitle}</p>
                <div className="mt-16 pt-8 border-t border-gray-300 w-24"></div>
                <p className="mt-4 font-serif italic text-gray-600">{t.writtenBy} {book.config.authorName}</p>
            </div>

            {/* Chapters & Sections */}
            <div className="p-16 lg:p-24 space-y-32">
                {book.chapters.map((chapter, cIdx) => (
                    <section key={chapter.id}>
                        {/* Chapter Title */}
                        <div className="mb-20">
                            <span className="text-9xl font-black text-gray-100 font-sans block leading-none -mb-10 -ml-4 select-none">
                                {String(cIdx + 1).padStart(2, '0')}
                            </span>
                            <h2 className="relative text-5xl font-serif font-bold text-gray-900 border-b-4 border-indigo-600 pb-6 inline-block pr-12">
                                {chapter.title}
                            </h2>
                            <p className="mt-8 text-xl text-gray-500 font-light leading-relaxed max-w-2xl">
                                {chapter.description}
                            </p>
                        </div>

                        {/* Sections */}
                        <div className="space-y-24">
                            {chapter.sections.map((section, sIdx) => (
                                <div key={sIdx} className="group">
                                    <div className="flex flex-col gap-8">
                                        <h3 className="font-sans text-2xl font-bold text-gray-800 flex items-center gap-3">
                                            <span className="w-2 h-2 bg-indigo-500 rounded-full"></span>
                                            {section.title}
                                        </h3>
                                        
                                        {section.imageUrl && (
                                            <div className="w-full overflow-hidden rounded-xl shadow-lg relative aspect-video bg-gray-100">
                                                <img 
                                                    src={section.imageUrl} 
                                                    alt={section.visualConcept}
                                                    className="w-full h-full object-cover transform transition-transform duration-700 group-hover:scale-105"
                                                    loading="lazy"
                                                />
                                                <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent p-4 opacity-0 group-hover:opacity-100 transition-opacity">
                                                    <p className="text-white text-xs font-mono">{section.visualConcept}</p>
                                                </div>
                                            </div>
                                        )}

                                        <div 
                                            className="prose prose-lg prose-slate max-w-none font-serif text-gray-600 leading-8 text-justify"
                                            dangerouslySetInnerHTML={{ __html: section.content || "..." }} 
                                        />
                                    </div>
                                </div>
                            ))}
                        </div>
                    </section>
                ))}
            </div>

            {/* Back Cover */}
            <div className="bg-slate-900 text-white p-24 text-center">
                <h3 className="font-sans font-bold text-2xl mb-4">IA Books</h3>
                <p className="text-gray-400">{t.backCoverDesc}</p>
                <p className="text-gray-500 text-xs mt-4">Powered by Fábio Arieira</p>
            </div>
        </div>
      </div>
    </div>
  );
};